# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]

# For lazy loading
# https://sheldon.cli.rs/Examples.html#deferred-loading-of-plugins-in-zsh
[plugins.zsh-defer]
github = "romkatv/zsh-defer"
[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.zsh-abbr]
inline = 'source /opt/homebrew/share/zsh-abbr/zsh-abbr.zsh'

[plugins.starship]
inline = 'eval "$(starship init zsh)"'

[plugins.atuin]
inline = 'eval "$(atuin init zsh)"'

[plugins.mise]
inline = 'eval "$(/opt/homebrew/bin/mise activate bash)"'